Repository e-rmkt/capstone-project-travel-app, pull requests merged in 2023-10, with the labels that each got.

#23 User Story 6: Add styling to TripDetails page
  components/DeleteButton/DeleteButton.styled.js
  components/DeleteButton/DeleteIcon.svg
  components/DeleteButton/index.js
  components/EditButton/EditButton.styled.js
  components/EditButton/EditIcon.svg
  components/EditButton/index.js
  components/TimePeriod/DateIcon.svg
  components/TimePeriod/TimePeriod.styled.js
  components/TimePeriod/index.js
  components/Trip/index.js
  components/TripDetails/TripDetails.styled.js
  components/TripDetails/index.js
  pages/trip/[id].js
  styles.js
Labels: enhancement 🚀, MVP ⭐️, design 🎨

#24 User Story 6: add styling to EditForm
  components/CancelButton/CancelButton.styled.js
  components/CreateButton/CreateButton.styled.js
  components/EditForm/index.js
  pages/forms/TripForm/[id].js
Labels: enhancement 🚀, MVP ⭐️, design 🎨

#22 Feat/trip counter and refactor form
  components/Counter/index.js
  components/EditForm/index.js
  components/Trip/index.js
  components/TripDetails/index.js
  components/TripForm/index.js
  db/models/Trip.js
  package-lock.json
  package.json
  pages/forms/TripForm/[id].js
  pages/forms/TripForm/index.js
  pages/trip/[id].js
Labels: enhancement 🚀

#30 user Story 6: Add styling to Counter component
  components/Counter/Counter.styled.js
  components/Counter/CounterIcon.svg
  components/Counter/index.js
  components/TripList/TripList.styled.js
Labels: design 🎨
