Repository e-rmkt/capstone-project-travel-app, pull requests merged in 2023-09, with the labels that each got.

#8 User Story 3: Create A Trip
  components/CancelButton/CancelButton.styled.js
  components/CancelButton/index.js
  components/CreateButton/CreateButton.styled.js
  components/CreateButton/index.js
  components/CreateTrip/CreateTrip.styled.js
  components/CreateTrip/index.js
  pages/api/trips/index.js
  pages/forms/TripForm/index.js
  pages/index.js
Labels: enhancement 🚀, MVP ⭐️

#11 User Story 4: Delete a Trip
  components/DeleteButton/DeleteButton.styled.js
  components/DeleteButton/index.js
  pages/api/trips/[id].js
  pages/trip/[id].js
Labels: enhancement 🚀, MVP ⭐️

#18 User Story 6: Add styling to TripList
  components/CreateTrip/CreateTrip.styled.js
  components/CreateTrip/index.js
  components/Location/index.js
  components/TimePeriod/index.js
  components/Trip/Trip.styled.js
  components/Trip/index.js
  components/TripList/TripList.styled.js
  components/TripList/index.js
  next.config.js
  pages/index.js
  styles.js
Labels: MVP ⭐️, design 🎨

#19 User Story 6: Add styling to Trip Form
  components/CancelButton/CancelButton.styled.js
  components/CancelButton/CancelIcon.svg
  components/CancelButton/index.js
  components/CreateButton/CreateButton.styled.js
  components/CreateButton/CreateIcon.svg
  components/CreateTrip/CreateTrip.styled.js
  components/Trip/index.js
  components/TripForm/TripForm.styled.js
  components/TripForm/index.js
  pages/forms/TripForm/index.js
  pages/index.js
Labels: MVP ⭐️, design 🎨

#21 User Story 6: Style Loading State
  components/TripList/index.js
  package-lock.json
  package.json
Labels: enhancement 🚀, design 🎨
